# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  issues:
    types: [opened]

#env:
#  PROJECT_URL: https://github.com/IamDum/web-blogs/projects/1
 # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 # MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    
      - uses: actions-ecosystem/action-add-labels@v1
        if: github.event.action == 'opened'
        with:
          github_token: ${{  secrets.GITHUB_TOKEN }}
          labels: newyuu
   
          
      # running ls
      - name: Run Add to Live squad
        run: |
          sh "${GITHUB_WORKSPACE}/.github/hh.sh"          
        env:
          PROJECT_URL: https://github.com/IamDum/web-blogs/projects/1
          INPUT_COLUMN_NAME: "Backlog"
          column_name: "Backlog"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         
