name: HHH Auto Assign issue to LiveSquad Project

# Controls when the action will run. 
on:
  milestone:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it d
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==21.0.1
          pip install pyGithub==1.55
      - run: |
          output=$(python ${GITHUB_WORKSPACE}/misc/github-actions/sync.py ${{ secrets.GITHUB_TOKEN }}  )
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}" 
          echo "::set-output name=logs::$output"
        id: step1
      - name: Print logs
        run: echo "${{ steps.step1.outputs.logs }}"

          
          
