name: Auto Assign issue to LiveSquad Project

# Controls when the action will run. 
on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: github.event.action == 'opened'
        with:
          github_token: ${{  secrets.GITHUB_TOKEN }}
          labels: new

      - name: Add to LiveSquad project
        run: |
          sh "${GITHUB_WORKSPACE}/.github/hh.sh"
        env:
          PROJECT_URL: 'https://github.com/IamDum/web-blogs/projects/1'
          INPUT_COLUMN_NAME: "Backlog"
          column_name: "Backlog"
          GITHUB_ACTOR: ${{ secrets.GITHUB_TOKEN }}
          TOKEN: ${{ secrets.VP_DEPLOY_SECRET }}
