# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  PROJECT_URL: https://github.com/IamDum/web-blogs/projects/1


  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo jq --version
          echo jq
          jq --version
          echo Add other actions to build,
          echo test, and deploy your project.
          
      # running ls
      - name: Run a ls
        run: |
          sh "${GITHUB_WORKSPACE}/.github/script.sh"          
        env:
          PROJECT_URL: https://github.com/IamDum/web-blogs/projects/1
          INPUT_COLUMN_NAME: "To do"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         
