name: Auto Assign issue to LiveSquad Project

# Controls when the action will run. 
on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it d
      - uses: actions/checkout@v2
      - run: |
          output=$(python ${GITHUB_WORKSPACE}/.github/sync.py v2.21)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}" 
          echo "::set-output name=changelog::$output"
        id: step1
      - name: Print changelog
        run: echo "${{ steps.step1.outputs.changelog }}"

          
          
