 
name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROJECT_URL: https://github.com/IamDum/NationalBank/projects/2

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Live Squad Project
    steps:
    - run: ls
          
